global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 10s
scrape_configs:
  - job_name: slow_control
    scrape_interval: 5s
    metrics_path:  /metrics
    scheme:  http
    static_configs:
    - targets: ['iotpy:8085']